name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: |
        cd mcp-server
        npm ci
    
    - name: Build
      run: |
        cd mcp-server
        npm run build
    
    - name: Publish to npm
      run: |
        cd mcp-server
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
  create-melpa-pr:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }}
    
    - name: Create MELPA recipe
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        cat > claude-code-emacs-recipe.el << EOF
        (claude-code-emacs
         :fetcher github
         :repo "yuya373/claude-code-emacs"
         :files ("*.el" (:exclude "test-*.el")))
        EOF
        
        echo "MELPA recipe created. Please submit this to MELPA manually:"
        cat claude-code-emacs-recipe.el
    
    - name: Upload MELPA recipe
      uses: actions/upload-artifact@v4
      with:
        name: melpa-recipe
        path: claude-code-emacs-recipe.el
