name: CI Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - '28.1'
          - '29.1'
          - 'snapshot'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Cache Emacs packages
      uses: actions/cache@v4
      id: cache-emacs-packages
      with:
        path: |
          ~/.emacs.d/elpa
          ~/.config/emacs/elpa
        key: ${{ runner.os }}-emacs-${{ matrix.emacs-version }}-packages-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-emacs-${{ matrix.emacs-version }}-packages-
          ${{ runner.os }}-emacs-${{ matrix.emacs-version }}-

    - name: Install dependencies
      run: make install-deps

    - name: Compile
      run: make compile

    - name: Run tests
      run: make test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-emacs-${{ matrix.emacs-version }}
        path: |
          *.log
          *.elc
